version: '3.8'

services:
  postgis:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/postgresql:/var/lib/postgresql/data  # Bind the host directory /data to the container's data directory
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes: {}

