name: carlisle-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - gdal
  - rasterio
  - geopandas
  - numpy
  - matplotlib
  - pandas
  - scipy
  - tqdm 
  - netCDF4
  - psycopg2
  - scikit-learn
  - python-dotenv
  - pytorch
  - torchvision
  - imageio
  - tabulate
  - psutil
    # Add any other pip-specific packages here
variables:
  GDAL_DISABLE_READDIR_ON_OPEN: "EMPTY_DIR"
  CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".shp,.wd"
  GDAL_CACHEMAX: "512"
