# Model names
LSTM_V1 = "LSTM_V1"
CNN1D_V1 = "1DCNN_V1"
PICNN1D_V1 = "PICNN1D_V1"
LSTM_SRR_V1 = "LSTM_SRR_V1"
USRR_1DCNN_V1 = "USSR_1DCNN_V1"
USSR_1DCNN_V2 = "USSR_1DCNN_V2"
USRR_UNET_V1 = "USSR_UNET_V1"
USRR_CNN1D_COMBINED = "USSR_CNN1D_COMBINED"
SRR_LSTM_COMBINED = "SRR_LSTM_COMBINED"
POD_BNN_V1 = "POD_BNN_V1"
TCN_V1 = "TCN_V1"
HDL_FM_V1 = "HDL_FM_V1"
USRR_LSTM = "USRR_LSTM_V1"

# Metrics
RMSE = "RMSE"
MRMSE = "mRMSE"
RMSE_T = "RMSE_t"
RMSE_S = "RMSE_s"
MRMSE_T = "mRMSE_t"
MRMSE_S = "mRMSE_s"
HITRATE = "Hitrate"
CSI = "CSI"
F2SCORE = "F2Score"
F3SCORE = "F3Score"
INFERENCE_TIMES = "Latency"
INFERENCE_MEMORY_USAGE = "Memory"
FLOPS = "FLOPs"
PARAMS = "Parameters"

#Paths
study_area = "carlisle"
PROJECT_ROOT = f"/home/91/23016891/projects/{study_area}"
OUTPUT_DIR = f"/data/{study_area}/out"
RUN_DIR = f"{OUTPUT_DIR}/runs"
PLOTS_OUTPUT_DIR = f"{OUTPUT_DIR}/plots"
SIMULATION_DATA_DIR = "/data/carlisle/simulation/DEM5m_2D"
GRAPH_OUTPUT_DIR = PLOTS_OUTPUT_DIR

DEM_FILE = f"/data/carlisle/simulation/Carlisle_5m.asc"
DATA_DIR = f"{PROJECT_ROOT}/data/{study_area}"
SIMULATION_OUTPUT_DIR =  f"/data/{study_area}/simulation_output"
