# Model names
LSTM_V1 = "LSTM_V1"
CNN1D_V1 = "1DCNN_V1"
PICNN1D_V1 = "PICNN1D_V1"
LSTM_SRR_V1 = "LSTM_SRR_V1"
USRR_1DCNN_V1 = "USSR_1DCNN_V1"
USSR_1DCNN_V2 = "USSR_1DCNN_V2"
USRR_UNET_V1 = "USSR_UNET_V1"
USRR_CNN1D_COMBINED = "USSR_CNN1D_COMBINED"
SRR_LSTM_COMBINED = "SRR_LSTM_COMBINED"
POD_BNN_V1 = "POD_BNN_V1"
TCN_V1 = "TCN_V1"
HDL_FM_V1 = "HDL_FM_V1"
USRR_LSTM = "USRR_LSTM_V1"


#Paths
PROJECT_ROOT = "/home/91/23016891/projects/carlisle"
DATA_DIR = f"{PROJECT_ROOT}/data/westport"
OUTPUT_DIR = f"/data/westport/out"
GRAPH_OUTPUT_DIR = f"{PROJECT_ROOT}/out"
RUN_DIR = f"{OUTPUT_DIR}/runs"git